site_name: DMOJ Docs
pages:
- Home: 'index.md'
- Site:
  - 'Installing the Site': 'site/installation.md'
  - 'Updating the Site': 'site/updating.md'
  - 'Managing Problems Through the Site Interface': 'site/managing_problems.md'
  - 'PDF Generation of Problem Statements': 'site/pdf_generation.md'
  - 'LaTeX Diagrams with Texoid': 'site/texoid.md'
  - 'reCAPTCHA Spam Registration Prevention': 'site/recaptcha.md'
  - 'SSL Proxying for User Content': 'site/ssl_content_proxy.md'
- Judge:
  - 'Linux Installation': 'judge/linux_installation.md'
  - 'Windows Installation': 'judge/windows_installation.md'
  - 'Colored Compiler Messages': 'judge/colored_compiler_messages.md'
  - 'Problem Format': 'judge/problem_format.md'
  - 'Problem Examples': 'judge/problem_examples.md'
  - 'Supported Languages': 'judge/supported_languages.md'
  - 'Status Codes': 'judge/status_codes.md'
- About:
    - 'License': 'about/LICENSE.md'
theme: readthedocs
markdown_extensions:
    - admonition
